version: "3.3"
services:
  tp4:
    build:
      context: .
      dockerfile: Dockerfile
    image: tp4
    ports:
      - "80:80"
    networks:
      node_net:
        ipv4_address: 172.16.238.4

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/16"
